name: HazelCopcutt
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b0bb2f38-5f68-45b0-b562-61c82e0415bc.jpg
layout_spectrum: 0.6510620582848787
typography_spectrum: 0.681014568079263
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#F6F792'
    - '#333745'
    - '#77C4D3'
    - '#DAEDE2'
    - '#EA2E49'
  brandStrength: 0.604706630576402
  lightness: 0.033116385573521256
  saturation: 0.16802542936056852
  rhythmicContrast: 0.31103446171619
title: Love Wisdom Time & Death
author:
  name: Hazel Copcutt
  url: 'http://hazelcopcutt.com'
  email: hazel@supernaturalstrangelove.com
content_rating:
  adult: true
